baseconfigs: &baseconfigs
  # benchmark configs ---------------
  case_type: Performance1536D500K
  drop_old: True
  load: True
  search_serial: True
  search_concurrent: True
  num_concurrency: 1,2,4,6,8,10,12,14,16,18,20,22,24
  concurrency_duration: 30
  # db configs ----------------------
  k: 15

milvusflat:
  <<: *baseconfigs
  db_label: milvusflat_4c16gb_500k

pgvectorflat:
  <<: *baseconfigs
  db_label: pgvectorflat_4c16gb_500k
  user_name: postgres
  db_name: postgres
  password: password
  maintenance_work_mem: 1GB
  max_parallel_workers: 4

elasticflat:
  <<: *baseconfigs
  db_label: elasticflat_4c16gb_500k
  port: 9200