baseconfigs: &baseconfigs
  # benchmark configs ---------------
  case_type: Performance1536D500K
  drop_old: True
  load: True
  search_serial: True
  search_concurrent: True
  num_concurrency: 1,8,16,24,32,40,48,56,64,72,80,88,96
  concurrency_duration: 30
  # db configs ----------------------
  k: 15

milvusflat:
  <<: *baseconfigs
  db_label: milvusflat_16c64gb_500k

pgvectorflat:
  <<: *baseconfigs
  db_label: pgvectorflat_16c64gb_500k
  user_name: postgres
  db_name: postgres
  password: password
  maintenance_work_mem: 2GB
  max_parallel_workers: 16

elasticflat:
  <<: *baseconfigs
  db_label: elasticflat_16c64gb_500k
  port: 9200