baseconfigs: &baseconfigs
  # benchmark configs ---------------
  case_type: Performance1536D500K
  drop_old: True
  load: True
  search_serial: True
  search_concurrent: True
  num_concurrency: 1,8,16,24,32,40
  concurrency_duration: 30
  # db configs ----------------------
  k: 100
  m: 16
  ef_construction: 128
  ef_search: &ef_search 128

milvushnsw:
  <<: *baseconfigs
  db_label: milvushnsw_16c64gb_500k

pgvectorhnsw:
  <<: *baseconfigs
  db_label: pgvectorhnsw_16c64gb_500k
  user_name: postgres
  db_name: postgres
  password: password
  maintenance_work_mem: 800MB
  max_parallel_workers: 3

elastichnsw:
  <<: *baseconfigs
  num_candidates: *ef_search
  db_label: elastichnsw_16c64gb_500k
  port: 9200