# python -m vectordb_bench.cli.vectordbbench milvushnsw --config-file hnsw_configs.yml --uri http://10.244.8.231:19530
milvushnsw:
  # Common configurations
  case_type: Performance1536D50K
  drop_old: True
  load: True
  search_serial: True
  search_concurrent: True
  num_concurrency: 1,5,10,15,20,25,30,35,40,45,50
  concurrency_duration: 30
  k: 100
  # HNSW configurations
  m: 16
  ef_construction: 128
  ef_search: 128
  # Milvus configurations
  db_label: milvushnsw
  uri: http://localhost:19530


# python -m vectordb_bench.cli.vectordbbench pgvectorhnsw --config-file hnsw_configs.yml --host 10.244.5.191
pgvectorhnsw:
  # Common configurations
  case_type: Performance1536D50K
  drop_old: True
  load: True
  search_serial: True
  search_concurrent: True
  num_concurrency: 1,5,10,15,20,25,30,35,40,45,50
  concurrency_duration: 30
  k: 100
  # HNSW configurations
  m: 16
  ef_construction: 128
  ef_search: 128
  # pgvector configurations
  db_label: pgvectorhnsw
  user_name: postgres
  db_name: postgres
  password: password
  host: localhost
  maintenance_work_mem: 64MB
  max_parallel_workers: 3

# python -m vectordb_bench.cli.vectordbbench elastichnsw --config-file hnsw_configs.yml --host 10.244.5.133
elastichnsw:
  # Common configurations
  case_type: Performance1536D50K
  drop_old: True
  load: True
  search_serial: True
  search_concurrent: True
  num_concurrency: 1,5,10,15,20,25,30,35,40,45,50
  concurrency_duration: 30
  k: 100
  # HNSW configurations
  m: 16
  ef_construction: 128
  ef_search: 128
  # pgvector configurations
  db_label: elastichnsw
  host: localhost
  port: 9200