baseconfigs: &baseconfigs
  # benchmark configs ---------------
  case_type: Performance1536D50K
  drop_old: True
  load: True
  search_serial: True
  search_concurrent: True
  num_concurrency: 1,2,4,6,8,10,12,14,16,18,20,22,24
  concurrency_duration: 30
  # db configs ----------------------
  k: 15 # Aus Experiment von Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks
  m: 16 # Default pgvector
  ef_construction: 64 # Default pgvector
  ef_search: &ef_search 40 # Default pgvector

milvushnsw:
  <<: *baseconfigs
  db_label: milvushnsw_4c16gb_50k

pgvectorhnsw:
  <<: *baseconfigs
  db_label: pgvectorhnsw_4c16gb_50k
  user_name: postgres
  db_name: postgres
  password: password
  maintenance_work_mem: 1GB
  max_parallel_workers: 4

elastichnsw:
  <<: *baseconfigs
  num_candidates: *ef_search
  db_label: elastichnsw_4c16gb_50k
  port: 9200