baseconfigs: &baseconfigs
  # benchmark configs ---------------
  case_type: Performance1536D500K
  drop_old: True
  load: True
  search_serial: True
  search_concurrent: True
  num_concurrency: 1,2,4,6,8,10,12,14,16,18,20,22,24
  concurrency_duration: 30
  # db configs ----------------------
  k: 15
  m: 16
  ef_construction: 64
  ef_search: &ef_search 40

milvushnsw:
  <<: *baseconfigs
  db_label: milvushnsw_4c16gb_500k

pgvectorhnsw:
  <<: *baseconfigs
  db_label: pgvectorhnsw_4c16gb_500k
  user_name: postgres
  db_name: postgres
  password: password
  maintenance_work_mem: 1GB
  max_parallel_workers: 4

elastichnsw:
  <<: *baseconfigs
  num_candidates: *ef_search
  db_label: elastichnsw_4c16gb_500k
  port: 9200