baseconfigs: &baseconfigs
  # benchmark configs ---------------
  case_type: Performance1536D50K
  drop_old: True
  load: True
  search_serial: True
  search_concurrent: True
  num_concurrency: 1,8,16,24,32,40,48,56,64,72,80,88,96
  concurrency_duration: 30
  # db configs ----------------------
  k: 15
  m: 16
  ef_construction: 64
  ef_search: &ef_search 40

milvushnsw:
  <<: *baseconfigs
  db_label: milvushnsw_16c64gb_50k

pgvectorhnsw:
  <<: *baseconfigs
  db_label: pgvectorhnsw_16c64gb_50k
  user_name: postgres
  db_name: postgres
  password: password
  maintenance_work_mem: 2GB
  max_parallel_workers: 16

elastichnsw:
  <<: *baseconfigs
  num_candidates: *ef_search
  db_label: elastichnsw_16c64gb_50k
  port: 9200